config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create show edit update destroy]
  namespace :admin do
    resources :users, only: %i[index destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :labeling_tasks, through: :labelings, source: :task
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true

  scope :create_new_sort, -> {order(created_at: :desc)}
  scope :time_limit_sort, -> {reorder(time_limit: :desc)}
  scope :name_select, -> (name){where("tasks.name LIKE ?", "%#{name}%")} # nameが混じるけ、tasksテーブルのっち指定する
  scope :status_select, -> (status){where(status: status)} # {where(status: params[:status])}
  scope :high_priority_sort, -> {reorder(priority: :asc)}
  
  enum status: {未着手: 0, 着手中: 1, 完了: 2}
  enum priority: {高: 0, 中: 1, 低: 2}

  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings, source: :label
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  before_validation {email.downcase!}
  has_secure_password
  validates :password, length: {minimum: 6}

  enum admin: {管理者: true, 一般: false}

  before_update :admin_is_not_change
  before_destroy :admin_is_not_delete

  private
  def admin_is_not_change
    throw(:abort) if User.where(admin: true).count == 1 && self.admin == "一般"
  end

  def admin_is_not_delete
    throw(:abort) if User.where(admin: true).count == 1 && self.admin == "管理者"
  end
  # admin_count = User.group(:admin).count
  #   if admin_count["管理者"] == 1
  #     User(current_user.id).admin = :管理者
  #     redirect_to admin_users_path, notice: "管理者は１人以上いないといけません"
  #   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :user_or_admin

  def index
    @users = User.select(:id, :name, :admin).includes(:tasks).page(params[:page]).per(10)
  end
  
  def destroy
    @user = User.find(params[:id])
    lost_user = @user.name
    @user.destroy
    redirect_to admin_users_path, notice: "#{lost_user}さんのアカウントを削除しました"
  end

  private
  def user_or_admin
    unless current_user.admin == "管理者"
      redirect_to tasks_path(current_user.id)
      flash[:danger] = "管理者権限がない為、アクセス出来ません！"
    end
  end
end

app/controllers/admin/uses_controller.rb
class Admin::UsesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include EnumHelper
  include SessionsHelper

  before_action :login_required

  private
  def login_required
    redirect_to new_session_path, notice: "ログインをして下さい" unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = current_user.tasks.includes(:user).create_new_sort
    if params[:time_limit_sort]
      @tasks = @tasks.time_limit_sort
    elsif params[:high_priority_sort]
      @tasks = @tasks.high_priority_sort
    end
    if params[:task].present?
      @tasks = @tasks.status_select(params[:task][:status]) if params[:task][:status].present?
      @tasks = @tasks.name_select(params[:task][:name]) if params[:task][:name].present?
      @tasks = @tasks.joins(:labels).where(labels: {id: params[:task][:label_id]}) if params[:task][:label_id].present?
    end
  @tasks = @tasks.page(params[:page]).per(10)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: "登録完了しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task), notice: "更新完了しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "削除しました"
  end

  private
  def task_params
    params.require(:task).permit(:name, :time_limit, :status, :priority, :content, {label_ids: []})
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :current_user_or_admin, only: %i[show edit update]
  before_action :logged_out_or_admin, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if logged_in? && current_user.admin == "管理者"
        redirect_to admin_users_path, notice: "#{@user.name}さんのアカウントを作成しました"
      else
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: "アカウント作成完了"
      end
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks.includes(:user).page(params[:page]).per(10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      if current_user.admin == "管理者"
        redirect_to admin_users_path, notice: "#{@user.name}さんのプロフィールを編集しました"
      else
        redirect_to user_path, notice: "プロフィール編集完了"
      end
    else
      render :edit
    end
  end

  # def destroy
  #   lost_name = @user.name
  #   @user.destroy
  #   redirect_to new_user_path, notice: "#{lost_name}さんのアカウントを削除しました"
  # end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def current_user_or_admin
    redirect_to tasks_path(current_user.id), notice: "他のユーザーのページは閲覧できません" unless @user == current_user || current_user.admin == "管理者"
  end

  def logged_out_or_admin
    redirect_to tasks_path(current_user.id), notice: "新規アカウント登録される場合は、ログアウトして下さい" unless logged_in? == false || current_user.admin == "管理者"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enum_helper.rb
module EnumHelper
  def select_from_enum(class_o, column)
    enum_list = class_o.send(column.to_s.pluralize)
    enum_list.map do |column_n, _value|
      [t("enums.#{class_o.to_s}.#{column}.#{column_n}"), column_n]
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/index.html.erb
<h3>ユーザー一覧</h3>
<br>
<%= form_with(model: @users, local: true, url: admin_users_path, scope: :user) do |f| %>
  <table>
    <tr>
      <th>ID</th>
      <th>ユーザー名</th>
      <th>権限</th>
      <th>タスク数</th>
      <th colspan="3"></th>
    </tr>
    <br>
    <% @users.each do |user| %>
      <tr>
        <td class="users_id"><%= user.id %></td>
        <td class="user_name"><%= user.name %></td>
        <td class="users_admin"><%= user.admin %></td>
        <td class="users_tasks"><%= user.tasks.size %></td>
        <td><button type="button" class="btn btn-success"><%= link_to '詳細', user_path(user.id) %></button></td>
        <td><button type="button" class="btn btn-info"><%= link_to '編集', edit_user_path(user.id) %></button></td>
        <td><button type="button" class="btn btn-danger"><%= link_to '削除', admin_user_path(user.id), method: :delete, id: "delete_#{user.id}", data: {confirm: '本当に削除しますか？'} %></button></td>
      </tr>
    <% end %>
  </table>
  <div>
    <br>
    <%= paginate @users %>
    <br>
    <%= link_to "新規ユーザー登録", new_user_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskChecker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Task Checker</h1>
    </header>
    <div>
      <table class="info_btn">
        <% if logged_in? %>
          <% if current_user.admin == "管理者" %>
            <th><%= link_to "管理者画面", admin_users_path %>|</th>
          <% end %>
          <th><%= link_to "マイページ", user_path(current_user.id) %>|</th>
          <th><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></th>
        <% else %>
          <th><%= link_to "新規登録", new_user_path %>|</th>
          <th><%= link_to "ログイン", new_session_path %></th>
        <% end %>
      </table>
      <br>
      <%= t('view.confirmation_sample') %>
      <br>
      <div>
      <% flash.each do |key, value| %>
        <h3><%= content_tag(:div, value, class: "#{key}") %></h3>
      <% end %>
      </div>
      <br>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      <br>
    </div>
    <footer>
      <%= link_to "タスクチェッカー TOP", tasks_path %>
    </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :"タスク：" %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :"終了期限：" %>
    <%= f.datetime_field :time_limit %>
    <br>
    <br>
    <%= f.label :"進捗：" %>
    <%= f.select :status, select_from_enum(Task, :status) %>
    <br>
    <br>
    <%= f.label :"優先度：" %>
    <%= f.select :priority, select_from_enum(Task, :priority) %>
    <br>
    <br>
    <%= f.label :" 概要 ：" %>
    <%= f.text_area :content %>
    <br>
    <br>
    <% Label.all.each do |label| %>
      <%= f.check_box :label_ids, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id] %>
      <%= label.name %>
    <% end %>
    </div>
  <br>
  <br>
  <% if @task.id.present? %>
    <%= f.submit :"更新" %>
  <% else %>
    <%= f.submit :"登録" %>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h3>タスク編集</h3>
<br>
<div>
  <%= render 'form', task: @task %>
  <br>
  <%= link_to "詳細", task_path %> | 
  <%= link_to "タスク一覧へ", tasks_path %>
  <br>
</div>

app/views/tasks/index.html.erb
<h3>タスク一覧</h3>
<br>
<%= form_with(local: true, url: tasks_path, method: :get, scope: :task) do |f| %>
  <table>
    <tr>
      <th>タスク</th>
      <th>終了期限</th>
      <th>進捗</th>
      <th>優先度</th>
      <th>ユーザー名</th>
      <th colspan="3"></th>
    </tr>
    <div>
      <%= link_to "作成日新しい順", tasks_path(create_new_sort: "true") %>|
      <%= link_to "終了期限遠い順", tasks_path(time_limit_sort: "true") %>|
      <%= link_to "優先度高い順", tasks_path(high_priority_sort: "true") %>
    </div>
    <div>
      <%= f.label :"タスク：" %>
      <%= f.text_field :name, value: "", placeholder: "タスク名" %>
      <%= f.label :"　進捗：" %>
      <%= f.select :status, select_from_enum(Task, :status), include_blank: true %>
      <%= f.label :"　ラベル：" %>
      <%= f.select :label_id, Label.all.collect{|l| [l.name, l.id]}, include_blank: true %>
      <%= f.submit "絞り込み" %>
    </div>
    <br>
    <% @tasks.each do |task| %>
      <tr>
        <td class="spec_test_name"><%= task.name %></td>
        <td class="task_time_limit"><%= l task.time_limit, format: :short %></td>
        <td class="task_status"><%= task.status %></td>
        <td class="task_priority"><%= task.priority %></td>
        <td class="task_user"><%= task.user.name %></td>
        <td><button type="button" class="btn btn-success"><%= link_to '詳細', task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-info"><%= link_to '編集', edit_task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-danger"><%= link_to '削除', task_path(task.id), method: :delete, data: {confirm: '本当に削除しますか？'} %></button></td>
      </tr>
    <% end %>
  </table>
  <div>
    <br>
    <%= paginate @tasks %>
    <br>
    <%= link_to "新タスク登録", new_task_path %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h3>新規タスク登録</h3>
<br>
<div>
  <%= render 'form', task: @task %>
  <br>
  <%= link_to "タスク一覧へ", tasks_path%>
  <br>
</div>

app/views/tasks/show.html.erb
<h3>タスク詳細</h3>
<br>
<div>
  <p>タスク：<%= @task.name %></p>
  <p>終了期限：<%= l @task.time_limit, format: :long %></p>
  <p>進捗：<%= @task.status %></p>
  <p>概要：<%= @task.content %></p>
  <p>ラベル：
    <% @task.label_ids.each do |label| %>
      <%= Label.find(label).name %> ,　
    <% end %>
  </p>


  <%= link_to "編集", edit_task_path %>|
  <%= link_to "タスク一覧へ", tasks_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :"ユーザー名：" %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :"メールアドレス：" %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :"パスワード：" %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.label :"パスワード(確認用)：" %>
    <%= f.password_field :password_confirmation %>
    <% if logged_in? && current_user.admin == "管理者" %>
      <br>
      <br>
      <%= f.label :"管理者権限：" %>
      <%= f.select :admin, select_from_enum(User, :admin) %>
    <% end %>
  </div>
  <br>
  <br>
  <% if @user.id.present? %>
    <%= f.submit :"更新" %>
    <br>
    <%= link_to "プロフィールに戻る", user_path %>
  <% else %>
    <%= f.submit :"登録" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h3>タスク編集</h3>
<br>
<div>
  <%= render 'form', task: @task %>
  <br>
</div>

app/views/users/new.html.erb
<h3>ユーザー登録</h3>
<br>
<div>
  <%= render 'form', user: @user %>
  <br>
</div>

app/views/users/show.html.erb
<h3><%= "#{@user.name}" %>さんのマイページ</h3>

<h3>タスク一覧</h3>
<br>
<%= form_with(model: @tasks, local: true, url: tasks_path, method: :get, scope: :task) do |f| %>
  <table>
    <tr>
      <th>タスク</th>
      <th>終了期限</th>
      <th>進捗</th>
      <th>優先度</th>
      <th>ユーザー名</th>
    </tr>
    <br>
    <% @tasks.each do |task| %>
      <tr>
        <td class="spec_test_name"><%= task.name %></td>
        <td class="task_time_limit"><%= l task.time_limit, format: :short %></td>
        <td class="task_status"><%= task.status %></td>
        <td class="task_priority"><%= task.priority %></td>
        <td class="task_user"><%= task.user.name %></td>
      </tr>
    <% end %>
  </table>
  <div>
    <br>
    <%= paginate @tasks %>
    <br>
    <%= link_to 'プロフィール編集', edit_user_path(@user.id) %>
  </div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/uses/create.html.erb
<h1>Uses#create</h1>
<p>Find me in app/views/uses/create.html.erb</p>